	/*this.TextoMeteo={"Tornado"
	,"Tormenta tropical"
	,"Huracan"
	,"Tormenta electrica severa"
	,"Tormenta electrica"
	,"Lluvia y nieve"
	,"lluvia y aguanieve"
	,"nieve y aguanieve"
	,"Llovizna helada"
	,"Llovizna"
	,"luvia helada"
	,"Ducha"
	,"Ducha"
	,"Copos de nieve"
	,"Nieve Ligera"
	,"Nieve que sopla"
	,"Nieve","Granizo"
	,"Agua nieve"
	,"Polvo"
	,"Brumoso"
	,"Neblina"
	,"Ahumado"
	,"Borrascoso"
	,"Ventoso","Frio","Nublado","Mayormente Nublado","Mayormente nublado"
					,"Parcialmente nublado","Parcialmente nublado","Despejado","Soleado","Justo","Justo","Lluvia y granizo","Caliente"
					,"Tormentas aisladas","Tormentas electricas dispersas","Tormentas electricas dispersas","Chuvascos dispersos","Nieve pesada"
					,"Nieve dispersa","Nieve pesada","Parcialmente nublado","Tormentoso","Ducha nieve","Chaparrones","No disponible"};
	this.GraphMeteo={6,18,6,15,15,23,23,23,17,17,17,18,18,23,21,23,23
					,24,21,13,13,5,5,20,6,7,25,9,8,9,8,3,2,3,2,24,2,15,15,15,17
					,23,21,23,8,18,23,17,45};
	*/